services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: dev
    image: namesprint-api-dev
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./api:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: dev
    image: namesprint-web-dev
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      NODE_ENV: development
    volumes:
      - ./web:/app
