FROM node:16 as base

WORKDIR /app
COPY ./web/package.json ./web/package-lock.json /app/
RUN npm ci

FROM base as production
COPY ./web /app
RUN npm run build

FROM nginx:stable as production-nginx
COPY --from=production /app/dist /usr/share/nginx/html
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

FROM base as dev
COPY ./web /app
CMD ["npm", "run", "dev", "--", "--host"]
