---
- name: Install deps
  ansible.builtin.package:
    name:
      - git
      - make
    state: present

- name: Disable password-based SSH authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart SSH

- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
    policy: deny

- name: Allow SSH, HTTP and HTTPS through UFW
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

