global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - 'primary.namesprint.io:9100'
          # - 'secondary.namesprint.io:9100'
  - job_name: 'nginx-exporter'
    static_configs:
      - targets:
        - 'primary.namesprint.io:9113'
        # - 'secondary.namesprint.io:9113'