TLDS_WITH_PRIORITY = {
    # premium
    ".com": {"priority": 1.5},
    ".net": {"priority": 1.6},
    ".org": {"priority": 1.7},
    ".io": {"priority": 1.7},
    ".dev": {"priority": 1.8},
    ".me": {"priority": 1.9},
    ".app": {"priority": 1.9},
    ".co": {"priority": 1.9},
    ".tech": {"priority": 1.9, "use_tokens": True},
    # common
    ".info": {"priority": 2.0},
    ".xyz": {"priority": 2.1},
    ".biz": {"priority": 2.2},
    ".be": {"priority": 2.3, "use_tokens": True},
    ".ca": {"priority": 2.4},
    ".de": {"priority": 2.4},
    ".eu": {"priority": 2.4, "use_tokens": True},
    ".fr": {"priority": 2.4},
    ".in": {"priority": 2.5},
    ".it": {"priority": 2.5},
    ".jp": {"priority": 2.5, "use_tokens": True},
    ".nl": {"priority": 2.5, "use_tokens": True},
    ".uk": {"priority": 2.6},
    ".us": {"priority": 2.6},
    ".au": {"priority": 2.7, "use_tokens": True},
    # '.co.nz': {'priority': 2.7},
    # '.es': {'priority': 2.7}, - This TLD has no whois server
    ".se": {"priority": 2.7},
    # '.tv': {'priority': 2.8}, # whois server is broken as of 05/04/23
    # '.ws': {'priority': 2.8, 'use_tokens': True}, - Has a low rate limit
    ".cc": {"priority": 2.9},
    ".cn": {"priority": 2.9},
    ".mx": {"priority": 2.9, "use_tokens": True},
    ".pro": {"priority": 2.9, "use_tokens": True},
    ".in": {"priority": 2.9},
    ".ua": {"priority": 2.9},
    ".tr": {"priority": 2.9},
    # ".vn": {"priority": 2.9},
    ".cn": {"priority": 2.9},
    ".gr": {"priority": 2.9},
    ".za": {"priority": 2.9},
    ".by": {"priority": 2.9},
    ".nz": {"priority": 2.9},
    ".cf": {"priority": 2.9},
    ".se": {"priority": 2.9},
    # '.sg': {'priority': 2.9,  'use_tokens': True},
    ".cc": {"priority": 2.9},
    ".rs": {"priority": 2.9},
    ".ga": {"priority": 2.9},
    ".ma": {"priority": 2.9},
    ".dk": {"priority": 2.9},
    ".hk": {"priority": 2.9},
    ".at": {"priority": 2.9},
    ".ml": {"priority": 2.9},
    ".no": {"priority": 2.9},
    # '.ph': {'priority': 2.9}, # no whois server
    ".fi": {"priority": 2.9},
    # '.to': {'priority': 2.9}, # whois server broken
    ".am": {"priority": 2.9},
    ".ee": {"priority": 2.9},
    ".si": {"priority": 2.9},
    ".im": {"priority": 2.9},
    ".is": {"priority": 2.9, "use_tokens": True},
    ".st": {"priority": 2.9},
    ".ac": {"priority": 2.9},
    ".sh": {"priority": 2.9},
    ".so": {"priority": 2.9, "use_tokens": True},
    ".gg": {"priority": 2.9, "use_tokens": True},
    # '.cm': {'priority': 2.9,  'use_tokens': True},
    # uncommon
    ".agency": {"priority": 3.0},
    ".band": {"priority": 3.0},
    ".blog": {"priority": 3.0},
    ".cash": {"priority": 3.0},
    ".club": {"priority": 3.0},
    ".community": {"priority": 3.0},
    ".company": {"priority": 3.0},
    ".contractors": {"priority": 3.0},
    ".cool": {"priority": 3.0},
    ".dating": {"priority": 3.0},
    ".design": {"priority": 3.0},
    ".digital": {"priority": 3.0},
    ".dog": {"priority": 3.0},
    ".email": {"priority": 3.0},
    ".events": {"priority": 3.0},
    ".exchange": {"priority": 3.0},
    ".expert": {"priority": 3.0},
    ".exposed": {"priority": 3.0},
    ".fail": {"priority": 3.0},
    ".fun": {"priority": 3.0},
    ".graphics": {"priority": 3.0},
    ".guide": {"priority": 3.0},
    ".guru": {"priority": 3.0},
    ".investments": {"priority": 3.0},
    ".legal": {"priority": 3.0},
    ".ltd": {"priority": 3.0},
    ".marketing": {"priority": 3.0},
    ".media": {"priority": 3.0},
    ".money": {"priority": 3.0},
    ".network": {"priority": 3.0},
    ".ninja": {"priority": 3.0},
    ".photography": {"priority": 3.0},
    ".photos": {"priority": 3.0},
    ".pictures": {"priority": 3.0},
    ".pizza": {"priority": 3.0},
    ".plus": {"priority": 3.0},
    ".recipes": {"priority": 3.0},
    ".reviews": {"priority": 3.0},
    ".sale": {"priority": 3.0},
    ".services": {"priority": 3.0},
    ".shop": {"priority": 3.0},
    ".solutions": {"priority": 3.0},
    ".space": {"priority": 3.0},
    ".store": {"priority": 3.0},
    ".studio": {"priority": 3.0},
    ".systems": {"priority": 3.0},
    ".technology": {"priority": 3.0},
    ".website": {"priority": 3.0},
    ".wiki": {"priority": 3.0},
    ".win": {"priority": 3.0},
    ".world": {"priority": 3.0},
    ".wtf": {"priority": 3.0},
    ".zone": {"priority": 3.0},
}
